In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import random
from scipy.spatial import distance as dst

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Ai LAB/Country-dataset.csv')
dataset = dataset.drop('country',1)
dataset =  dataset.to_numpy()
print(dataset)

In [ ]:
class KMC:
  def __init__(self, k):
    self.k = k


  def initial_centroids(self, data):
    centroids = []
    for i in range(self.k):
      centroids.append(data[random.randint(0,len(data)-1)])
    return np.array(centroids)


  def find_cluster_centroids(self, data, centroids):
    clust1 = []
    clust2 = []
    clust3 = []
    while True:
      for i in data:
        distance = []
        for j in centroids:
          distance.append(dst.euclidean(j,i))
        if distance[0] < distance[1] and distance[0] < distance[2]:
          clust1.append(i)
        elif distance[1] < distance[0] and distance[1] < distance[2]:
          clust2.append(i)
        else:
          clust3.append(i)
      cnew1 = np.array(clust1).mean(axis = 0)
      cnew2 = np.array(clust2).mean(axis = 0)
      cnew3 = np.array(clust3).mean(axis = 0)
      if centroids[0].all() == cnew1.all() and centroids[1].all() == cnew2.all() and centroids[2].all() == cnew3.all():
        break
      else:
        clust1.clear()
        clust2.clear()
        clust3.clear()
        centroids[0] = cnew1
        centroids[1] = cnew2
        centroids[2] = cnew3
    return centroids, clust1, clust2, clust3

In [ ]:
KMC = KMC(3)
centroids = KMC.initial_centroids(data)
final_centroids, cluster1, cluster2, clsuter3 = KMC.find_cluster_centroids(data,centroids)

In [ ]:
print(final_centroids)
print(cluster1)
print(cluster2)
print(clsuter3)

[[7.64e+01 7.47e+01 4.11e+04 4.44e+04]
 [2.69e+01 5.71e+01 9.92e+03 6.23e+03]
 [1.35e+01 1.94e+01 4.28e+03 1.04e+03]]
[array([1.98e+01, 2.09e+01, 4.14e+04, 5.19e+04]), array([   51.3,    47.8, 43200. , 46900. ]), array([   35. ,    43.7, 22900. , 28000. ]), array([   69.5,    50.9, 41100. , 20700. ]), array([   76.4,    74.7, 41100. , 44400. ]), array([6.74e+01, 2.80e+01, 8.06e+04, 3.53e+04]), array([2.91e+01, 3.10e+01, 4.07e+04, 4.74e+04]), array([   50.2,    57.5, 33900. , 30800. ]), array([5.05e+01, 4.36e+01, 4.40e+04, 5.80e+04]), array([3.87e+01, 3.74e+01, 3.98e+04, 4.62e+04]), array([2.68e+01, 2.81e+01, 3.69e+04, 4.06e+04]), array([4.23e+01, 3.71e+01, 4.04e+04, 4.18e+04]), array([2.21e+01, 3.07e+01, 2.87e+04, 2.69e+04]), array([   53.4,    43.3, 38800. , 41900. ]), array([  103. ,    86.5, 45700. , 48700. ]), array([   35. ,    32.9, 29600. , 30600. ]), array([2.52e+01, 2.72e+01, 3.62e+04, 3.58e+04]), array([1.50e+01, 1.36e+01, 3.58e+04, 4.45e+04]), array([6.67e+01, 3.04e+01, 7.52