In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
path = "/content/diabetes2.csv"

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv(path)

display(df)


Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0        148             72             35        0  33.6   
1         85             66             29        0  26.6   
2        183             64              0        0  23.3   
3         89             66             23       94  28.1   
4        137             40             35      168  43.1   
..       ...            ...            ...      ...   ...   
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 8 columns]

In [7]:
npArray=df.to_numpy()
display(npArray)


array([[148.   ,  72.   ,  35.   , ...,   0.627,  50.   ,   1.   ],
       [ 85.   ,  66.   ,  29.   , ...,   0.351,  31.   ,   0.   ],
       [183.   ,  64.   ,   0.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [121.   ,  72.   ,  23.   , ...,   0.245,  30.   ,   0.   ],
       [126.   ,  60.   ,   0.   , ...,   0.349,  47.   ,   1.   ],
       [ 93.   ,  70.   ,  31.   , ...,   0.315,  23.   ,   0.   ]])

In [8]:
print(type(npArray))
print(npArray)


<class 'numpy.ndarray'>
[[148.     72.     35.    ...   0.627  50.      1.   ]
 [ 85.     66.     29.    ...   0.351  31.      0.   ]
 [183.     64.      0.    ...   0.672  32.      1.   ]
 ...
 [121.     72.     23.    ...   0.245  30.      0.   ]
 [126.     60.      0.    ...   0.349  47.      1.   ]
 [ 93.     70.     31.    ...   0.315  23.      0.   ]]


In [9]:
from sklearn import preprocessing
normArray = preprocessing.normalize(npArray)
print(normArray)

[[0.82807841 0.40284896 0.19582935 ... 0.00350814 0.27975622 0.00559512]
 [0.71606575 0.55600399 0.24430478 ... 0.00295693 0.26115339 0.        ]
 [0.92484014 0.32344136 0.         ... 0.00339613 0.16172068 0.00505377]
 ...
 [0.65158849 0.38772208 0.12385566 ... 0.00131933 0.16155087 0.        ]
 [0.83828547 0.39918356 0.         ... 0.00232192 0.31269379 0.00665306]
 [0.73607517 0.55403507 0.24535839 ... 0.00249316 0.18204009 0.        ]]


In [10]:
import random
TrainSet = []
TestSet =[]

random.shuffle(normArray)

for i in range(len(normArray)):
  R = random.random()
  # print(R)
  if R>=0 and R<=0.8:
    TrainSet.append(normArray[i])
  else:
    TestSet.append(normArray[i])

print("Train Set........................................")
for i in range(len(TrainSet)):
   print(TrainSet[i])




Train Set........................................
[0.82807841 0.40284896 0.19582935 0.         0.18799618 0.00350814
 0.27975622 0.00559512]
[0.92484014 0.32344136 0.         0.         0.11775287 0.00339613
 0.16172068 0.00505377]
[0.59638065 0.17412574 0.15236002 0.73132809 0.18762048 0.00995999
 0.14365373 0.00435314]
[0.71606575 0.55600399 0.24430478 0.         0.22408646 0.00295693
 0.26115339 0.        ]
[0.92484014 0.32344136 0.         0.         0.11775287 0.00339613
 0.16172068 0.00505377]
[0.92935224 0.         0.         0.         0.28527073 0.0010829
 0.23435839 0.        ]
[0.82807841 0.40284896 0.19582935 0.         0.18799618 0.00350814
 0.27975622 0.00559512]
[3.35724500e-01 1.19292970e-01 7.66883376e-02 9.25372607e-01
 5.19776510e-02 2.69261274e-04 9.03218199e-02 1.70418528e-03]
[0.92484014 0.32344136 0.         0.         0.11775287 0.00339613
 0.16172068 0.00505377]
[0.88175567 0.38839238 0.         0.         0.19944474 0.00281847
 0.17845055 0.00524855]
[0.566019

In [11]:
print("Test Set........................................")
for i in range(len(TestSet)):
   print(TestSet[i])

Test Set........................................
[0.71606575 0.55600399 0.24430478 0.         0.22408646 0.00295693
 0.26115339 0.        ]
[0.71606575 0.55600399 0.24430478 0.         0.22408646 0.00295693
 0.26115339 0.        ]
[0.92484014 0.32344136 0.         0.         0.11775287 0.00339613
 0.16172068 0.00505377]
[0.81042823 0.51699732 0.         0.         0.17885313 0.00140428
 0.20959351 0.        ]
[0.58848023 0.43640107 0.15207916 0.62154092 0.18580106 0.00110423
 0.13885489 0.        ]
[0.82807841 0.40284896 0.19582935 0.         0.18799618 0.00350814
 0.27975622 0.00559512]
[0.56601953 0.36283303 0.23221314 0.63858614 0.22495648 0.00179965
 0.18867318 0.00725666]
[0.87845363 0.40337156 0.         0.         0.17837987 0.00202134
 0.18375816 0.00448191]
[0.88175567 0.38839238 0.         0.         0.19944474 0.00281847
 0.17845055 0.00524855]
[0.82807841 0.40284896 0.19582935 0.         0.18799618 0.00350814
 0.27975622 0.00559512]
[0.71274079 0.46976098 0.0890926  0.43736

In [12]:
Glucose = []
BloodPressure = []
SkinThickness = []
Insulin = []
BMI = []
DiabetesPer = []
Age = []
Outcome = []



for i in range(len(TrainSet)):
  Glucose.append(TrainSet[i][0])
  BloodPressure.append(TrainSet[i][1])
  SkinThickness.append(TrainSet[i][2])
  Insulin.append(TrainSet[i][3])
  BMI.append(TrainSet[i][4])
  DiabetesPer.append(TrainSet[i][5])
  Age.append(TrainSet[i][6])
  Outcome.append(TrainSet[i][7])

def avg(arr):
  s = sum(arr)
  a = s/len(arr)
  print(a)

avg(Glucose)
avg(BloodPressure)
avg(SkinThickness)
avg(Insulin)
avg(BMI)
avg(DiabetesPer)
avg(Age)
avg(Outcome)

    

0.6829024613601018
0.40609565749486237
0.10221209265118067
0.30775596432199587
0.18674065572892704
0.0027770319677113903
0.1990436359649419
0.002031693448482512
